# Generated by Django 4.1 on 2024-03-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('発生日', models.DateField(verbose_name='発生日')),
                ('発生時間', models.TimeField(verbose_name='発生時間')),
                ('発生場所', models.CharField(max_length=255, verbose_name='発生場所')),
                ('事件名', models.CharField(max_length=255, verbose_name='事件名')),
                ('事件の概要', models.TextField(verbose_name='事件の概要')),
                ('被疑者の人定事項', models.CharField(blank=True, max_length=255, verbose_name='被疑者の人定事項')),
                ('被害者の人定事項', models.CharField(blank=True, max_length=255, verbose_name='被害者の人定事項')),
                ('関係者の人定事項', models.CharField(blank=True, max_length=255, verbose_name='関係者の人定事項')),
            ],
        ),
    ]
