# Generated by Django 4.1 on 2024-03-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0002_crime_division_delete_event_crime_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='detail',
            new_name='crime_fact',
        ),
        migrations.RenameField(
            model_name='crime',
            old_name='title',
            new_name='crime_name',
        ),
        migrations.AddField(
            model_name='crime',
            name='crime_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='crime_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='crime_name_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='crime_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='crime_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='crime_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='suspect_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='suspect_birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='suspect_honseki',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='suspect_job',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crime',
            name='suspect_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
