# Generated by Django 4.1 on 2024-03-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0003_rename_detail_crime_crime_fact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_end_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_fact',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_start_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
