# Generated by Django 4.1 on 2024-03-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0004_alter_crime_crime_end_date_alter_crime_crime_fact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='suspect_birthday',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
