# Generated by Django 4.1 on 2024-03-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordapp', '0005_alter_crime_suspect_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='crime_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='crime',
            name='suspect_birthday',
            field=models.DateField(null=True),
        ),
    ]
